#! /bin/sh

# disable dependency trackeing for OS X with multiply arch option's
# automake -i --gnu --add-missing

aclocal \
&& automake -i --gnu --add-missing \
&& autoconf

# os x users might use glibtoolize -f
libtoolize -f
